services:
  seq:
    restart: always
    image: datalust/seq
    ports:
        - "${SEQ_UI_PORT:-38083}:80"
        - "${SEQ_LOG_PORT:-38084}:5341"
    environment:
        - ACCEPT_EULA=Y
  db:
    restart: always
    image: postgres:12
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  fider:
    restart: always
    image: getfider/fider:PR_1069
    ports:
      - "${FIDER_PORT:-38080}:3000"
    environment:
      - BASE_URL
      - DATABASE_URL
      - JWT_SECRET
      - EMAIL_NOREPLY
      # Either EMAIL_MAILGUN_* or EMAIL_SMTP_* or EMAIL_AWSSES_* is required
      - EMAIL_MAILGUN_API
      - EMAIL_MAILGUN_DOMAIN
      - EMAIL_SMTP_HOST
      - EMAIL_SMTP_PORT
      - EMAIL_SMTP_USERNAME
      - EMAIL_SMTP_PASSWORD
      - EMAIL_SMTP_ENABLE_STARTTLS
      - EMAIL_AWSSES_REGION
      - EMAIL_AWSSES_ACCESS_KEY_ID
      - EMAIL_AWSSES_SECRET_ACCESS_KEY
    depends_on:
      - "db"
      - "email"
  email:
    restart: always
    image: rnwood/smtp4dev
    ports:
        - "${SMTP4DEV_PORT:-38081}:80"
  adminer:
    image: adminer
    restart: always
    ports:
      - 38082:8080
