version: '2'
services:
  db:
    restart: always
    image: postgres:12
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  fider:
    restart: always
    image: getfider/fider:stable
    ports:
      - "${FIDER_PORT:-80}:3000"
    environment:
      - HOST_DOMAIN
      - DATABASE_URL
      - JWT_SECRET
      - EMAIL_NOREPLY
      # Either EMAIL_MAILGUN_* or EMAIL_SMTP_* or EMAIL_AWSSES_* is required
      - EMAIL_MAILGUN_API
      - EMAIL_MAILGUN_DOMAIN
      - EMAIL_SMTP_HOST
      - EMAIL_SMTP_PORT
      - EMAIL_SMTP_USERNAME
      - EMAIL_SMTP_PASSWORD
      - EMAIL_SMTP_ENABLE_STARTTLS
      - EMAIL_AWSSES_REGION
      - EMAIL_AWSSES_ACCESS_KEY_ID
      - EMAIL_AWSSES_SECRET_ACCESS_KEY
    depends_on:
      - "db"
      - "email"
  email:
    restart: always
    image: rnwood/smtp4dev
    ports:
        - "${SMTP4DEV_PORT:-5000}:80"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080